package com.example.sessionauth.service;

import java.io.IOException;
import java.io.OutputStream;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.stream.IntStream;

import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.util.WorkbookUtil;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.example.sessionauth.model.SpnRecordBatchRequest;
import com.example.sessionauth.model.SpnUploadRequest;

import jakarta.annotation.PostConstruct;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.ObjectMapper;

@Service
public class SpnDataService {

    public static final int PAGE_SIZE = 10;

    private static final int EXCEL_CELL_CHARACTER_LIMIT = 32767;
    private static final String INSERT_RECORD_SQL = """
            INSERT INTO spn_records (upload_id, category_key, row_number, record_json, search_text)
            VALUES (?, ?, ?, ?, ?)
            """;

    private final JdbcTemplate jdbcTemplate;
    private final ObjectMapper objectMapper;

    public SpnDataService(JdbcTemplate jdbcTemplate, ObjectMapper objectMapper) {
        this.jdbcTemplate = jdbcTemplate;
        this.objectMapper = objectMapper;
    }

    @PostConstruct
    @SuppressWarnings("unused")
    void initializeSchema() {
        // SPN data uses JDBC tables; idempotent creation keeps saved imports across restarts.
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS spn_uploads (
                    id VARCHAR(36) PRIMARY KEY,
                    owner VARCHAR(50) NOT NULL,
                    file_name VARCHAR(255) NOT NULL,
                    file_size BIGINT NOT NULL,
                    file_format VARCHAR(40),
                    created_value VARCHAR(20),
                    data_date VARCHAR(20),
                    organization VARCHAR(500),
                    record_count INT NOT NULL,
                    imported_at TIMESTAMP NOT NULL,
                    completed BOOLEAN NOT NULL DEFAULT FALSE
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS spn_categories (
                    upload_id VARCHAR(36) NOT NULL,
                    category_key VARCHAR(512) NOT NULL,
                    label VARCHAR(1000) NOT NULL,
                    record_count INT NOT NULL,
                    columns_json CLOB NOT NULL,
                    PRIMARY KEY (upload_id, category_key)
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS spn_records (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    upload_id VARCHAR(36) NOT NULL,
                    category_key VARCHAR(512) NOT NULL,
                    row_number INT NOT NULL,
                    record_json CLOB NOT NULL,
                    search_text VARCHAR(16000) NOT NULL,
                    UNIQUE (upload_id, category_key, row_number)
                )
                """);
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_spn_upload_owner ON spn_uploads(owner, completed, imported_at)");
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_spn_record_page ON spn_records(upload_id, category_key, row_number)");
    }

    @Transactional
    public String createUpload(String owner, SpnUploadRequest request) {
        if (request.fileName() == null || request.fileName().isBlank() || request.categories() == null
                || request.categories().isEmpty()) {
            throw new IllegalArgumentException("File name and parsed categories are required.");
        }

        String uploadId = UUID.randomUUID().toString();
        jdbcTemplate.update("""
                INSERT INTO spn_uploads (id, owner, file_name, file_size, file_format, created_value,
                                         data_date, organization, record_count, imported_at, completed)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, FALSE)
                """, uploadId, owner, request.fileName(), request.fileSize(), request.format(), request.created(),
                request.dataDate(), request.organization(), request.recordCount(), Timestamp.from(Instant.now()));

        jdbcTemplate.batchUpdate("""
                INSERT INTO spn_categories (upload_id, category_key, label, record_count, columns_json)
                VALUES (?, ?, ?, ?, ?)
                """, request.categories(), request.categories().size(), (statement, category) -> {
                    statement.setString(1, uploadId);
                    statement.setString(2, category.key());
                    statement.setString(3, category.label());
                    statement.setInt(4, category.recordCount());
                    statement.setString(5, writeJson(category.columns()));
                });
        return uploadId;
    }

    @Transactional
    public int saveRecordBatch(String owner, String uploadId, SpnRecordBatchRequest batch) {
        requireOwnedIncompleteUpload(owner, uploadId);
        if (batch.categoryKey() == null || batch.startRow() < 0 || batch.records() == null || batch.records().isEmpty()) {
            throw new IllegalArgumentException("A category, non-negative row offset, and records are required.");
        }
        Integer categoryCount = jdbcTemplate.queryForObject(
                "SELECT record_count FROM spn_categories WHERE upload_id = ? AND category_key = ?",
                Integer.class, uploadId, batch.categoryKey());
        if (categoryCount == null || batch.startRow() + batch.records().size() > categoryCount) {
            throw new IllegalArgumentException("Record batch does not match an uploaded category.");
        }

        List<StoredRecord> indexedRecords = IntStream.range(0, batch.records().size())
                .mapToObj(index -> new StoredRecord(batch.startRow() + index, batch.records().get(index)))
                .toList();
        jdbcTemplate.batchUpdate(INSERT_RECORD_SQL, indexedRecords, indexedRecords.size(), (statement, row) -> {
            String recordJson = writeJson(row.payload());
            statement.setString(1, uploadId);
            statement.setString(2, batch.categoryKey());
            statement.setInt(3, row.rowNumber());
            statement.setString(4, recordJson);
            statement.setString(5, searchableText(recordJson));
        });
        return batch.records().size();
    }

    @Transactional
    public void completeUpload(String owner, String uploadId) {
        requireOwnedIncompleteUpload(owner, uploadId);
        Integer expected = jdbcTemplate.queryForObject(
                "SELECT COALESCE(SUM(record_count), 0) FROM spn_categories WHERE upload_id = ?", Integer.class, uploadId);
        Integer saved = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM spn_records WHERE upload_id = ?", Integer.class, uploadId);
        if (!expected.equals(saved)) {
            throw new IllegalStateException("Upload is incomplete: expected " + expected + " records but saved " + saved + ".");
        }
        // Incomplete uploads stay out of the dashboard's latest-import query.
        jdbcTemplate.update("UPDATE spn_uploads SET completed = TRUE WHERE id = ? AND owner = ?", uploadId, owner);
    }

    @Transactional
    public void deleteUpload(String owner, String uploadId) {
        jdbcTemplate.update("DELETE FROM spn_records WHERE upload_id = ? AND EXISTS (SELECT 1 FROM spn_uploads WHERE id = ? AND owner = ?)",
                uploadId, uploadId, owner);
        jdbcTemplate.update("DELETE FROM spn_categories WHERE upload_id = ? AND EXISTS (SELECT 1 FROM spn_uploads WHERE id = ? AND owner = ?)",
                uploadId, uploadId, owner);
        jdbcTemplate.update("DELETE FROM spn_uploads WHERE id = ? AND owner = ?", uploadId, owner);
    }

        @Transactional
        public Map<String, Object> createRecord(String owner, String uploadId, String categoryKey, Map<String, Object> values) {
        requireOwnedCompleteUpload(owner, uploadId);
        List<String> columns = categoryColumns(uploadId, categoryKey);
        validateRecordValues(columns, values);
        Integer nextRowNumber = jdbcTemplate.queryForObject(
            "SELECT COALESCE(MAX(row_number), -1) + 1 FROM spn_records WHERE upload_id = ? AND category_key = ?",
            Integer.class, uploadId, categoryKey);
        String json = writeJson(values);
        jdbcTemplate.update(INSERT_RECORD_SQL, uploadId, categoryKey, nextRowNumber, json, searchableText(json));
        Long recordId = jdbcTemplate.queryForObject(
            "SELECT id FROM spn_records WHERE upload_id = ? AND category_key = ? AND row_number = ?",
            Long.class, uploadId, categoryKey, nextRowNumber);
        jdbcTemplate.update("UPDATE spn_categories SET record_count = record_count + 1 WHERE upload_id = ? AND category_key = ?",
            uploadId, categoryKey);
        jdbcTemplate.update("UPDATE spn_uploads SET record_count = record_count + 1 WHERE id = ? AND owner = ?",
            uploadId, owner);
        return recordView(recordId, values);
        }

        @Transactional
        public Map<String, Object> updateRecord(String owner, String uploadId, long recordId, Map<String, Object> values) {
        requireOwnedCompleteUpload(owner, uploadId);
        List<String> categoryKeys = jdbcTemplate.query("SELECT category_key FROM spn_records WHERE id = ? AND upload_id = ?",
            (result, rowNumber) -> result.getString("category_key"), recordId, uploadId);
        if (categoryKeys.isEmpty()) throw new IllegalArgumentException("Record not found.");
        validateRecordValues(categoryColumns(uploadId, categoryKeys.get(0)), values);
        String json = writeJson(values);
        jdbcTemplate.update("UPDATE spn_records SET record_json = ?, search_text = ? WHERE id = ? AND upload_id = ?",
            json, searchableText(json), recordId, uploadId);
        return recordView(recordId, values);
        }

        @Transactional
        public void deleteRecord(String owner, String uploadId, long recordId) {
        requireOwnedCompleteUpload(owner, uploadId);
        List<String> categoryKeys = jdbcTemplate.query("SELECT category_key FROM spn_records WHERE id = ? AND upload_id = ?",
            (result, rowNumber) -> result.getString("category_key"), recordId, uploadId);
        if (categoryKeys.isEmpty()) throw new IllegalArgumentException("Record not found.");
        String categoryKey = categoryKeys.get(0);
        jdbcTemplate.update("DELETE FROM spn_records WHERE id = ? AND upload_id = ?", recordId, uploadId);
        jdbcTemplate.update("UPDATE spn_categories SET record_count = record_count - 1 WHERE upload_id = ? AND category_key = ?",
            uploadId, categoryKey);
        jdbcTemplate.update("UPDATE spn_uploads SET record_count = record_count - 1 WHERE id = ? AND owner = ?",
            uploadId, owner);
        }

    public Map<String, Object> latestUpload(String owner) {
        List<Map<String, Object>> uploads = jdbcTemplate.query("""
                SELECT id, file_name, file_size, file_format, created_value, data_date, organization, record_count
                FROM spn_uploads WHERE owner = ? AND completed = TRUE
                ORDER BY imported_at DESC LIMIT 1
            """, (result, rowNumber) -> {
                Map<String, Object> upload = new LinkedHashMap<>();
                upload.put("id", result.getString("id"));
                upload.put("fileName", result.getString("file_name"));
                upload.put("fileSize", result.getLong("file_size"));
                upload.put("format", result.getString("file_format"));
                upload.put("created", result.getString("created_value"));
                upload.put("dataDate", result.getString("data_date"));
                upload.put("organization", result.getString("organization"));
                upload.put("recordCount", result.getInt("record_count"));
                return upload;
            }, owner);
        if (uploads.isEmpty()) return null;

        Map<String, Object> upload = uploads.get(0);
        String uploadId = (String) upload.get("id");
        List<Map<String, Object>> categories = jdbcTemplate.query("""
                SELECT category_key, label, record_count, columns_json
                FROM spn_categories WHERE upload_id = ? ORDER BY label
                """, (result, rowNumber) -> {
                    Map<String, Object> category = new LinkedHashMap<>();
                    category.put("key", result.getString("category_key"));
                    category.put("label", result.getString("label"));
                    category.put("recordCount", result.getInt("record_count"));
                    category.put("columns", readColumns(result.getString("columns_json")));
                    return category;
                }, uploadId);
        upload.put("categories", categories);
        return upload;
    }

    public Map<String, Object> pageRecords(String owner, String uploadId, String categoryKey, int page, String query) {
        requireOwnedCompleteUpload(owner, uploadId);
        if (page < 0 || categoryKey == null) throw new IllegalArgumentException("A category and non-negative page are required.");

        String normalizedQuery = query == null ? "" : query.trim().toLowerCase();
        String predicate = normalizedQuery.isEmpty() ? "" : " AND search_text LIKE ?";
        List<Object> parameters = new ArrayList<>(List.of(uploadId, categoryKey));
        if (!normalizedQuery.isEmpty()) parameters.add("%" + normalizedQuery + "%");
        // Use the same filter for the count and rows so the page range matches search results.
        Integer total = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM spn_records WHERE upload_id = ? AND category_key = ?" + predicate,
                Integer.class, parameters.toArray());

        parameters.add(PAGE_SIZE);
        parameters.add((long) page * PAGE_SIZE);
        List<Map<String, Object>> records = jdbcTemplate.query("""
            SELECT id, record_json FROM spn_records WHERE upload_id = ? AND category_key = ?
            """ + predicate + " ORDER BY row_number LIMIT ? OFFSET ?", (result, rowNumber) ->
            recordView(result.getLong("id"), readRecord(result.getString("record_json"))),
                parameters.toArray());
        int totalRecords = total == null ? 0 : total;
        Map<String, Object> response = new LinkedHashMap<>();
        response.put("items", records);
        response.put("page", page);
        response.put("pageSize", PAGE_SIZE);
        response.put("totalRecords", totalRecords);
        response.put("totalPages", Math.max(1, (int) Math.ceil((double) totalRecords / PAGE_SIZE)));
        return response;
    }

    private List<String> categoryColumns(String uploadId, String categoryKey) {
        List<String> columnsJson = jdbcTemplate.query("SELECT columns_json FROM spn_categories WHERE upload_id = ? AND category_key = ?",
                (result, rowNumber) -> result.getString("columns_json"), uploadId, categoryKey);
        if (columnsJson.isEmpty()) throw new IllegalArgumentException("Category not found.");
        return readColumns(columnsJson.get(0));
    }

    private void validateRecordValues(List<String> columns, Map<String, Object> values) {
        if (values == null || !columns.containsAll(values.keySet())) {
            throw new IllegalArgumentException("Record values must use fields defined for this category.");
        }
    }

    private Map<String, Object> recordView(long recordId, Map<String, Object> values) {
        Map<String, Object> item = new LinkedHashMap<>();
        item.put("id", recordId);
        item.put("values", values);
        return item;
    }

    public void validateExcelExport(String owner, String uploadId) {
        requireOwnedCompleteUpload(owner, uploadId);
    }

    public void writeExcelExport(String owner, String uploadId, OutputStream output) throws IOException {
        requireOwnedCompleteUpload(owner, uploadId);
        SXSSFWorkbook workbook = new SXSSFWorkbook(100);
        try (workbook) {
            workbook.setCompressTempFiles(true);
            List<ExportCategory> categories = jdbcTemplate.query("""
                    SELECT category_key, label, columns_json
                    FROM spn_categories WHERE upload_id = ? ORDER BY label
                    """, (result, rowNumber) -> new ExportCategory(
                    result.getString("category_key"), result.getString("label"), readColumns(result.getString("columns_json"))), uploadId);

            for (ExportCategory category : categories) {
                List<String> columns = category.columns();
                List<Integer> chunkCounts = exportColumnChunkCounts(uploadId, category);
                Sheet sheet = workbook.createSheet(uniqueSheetName(workbook, category.label()));
                Row header = sheet.createRow(0);
                int excelColumnIndex = 0;
                for (int columnIndex = 0; columnIndex < columns.size(); columnIndex++) {
                    for (int chunkIndex = 0; chunkIndex < chunkCounts.get(columnIndex); chunkIndex++) {
                        String headerValue = chunkIndex == 0 ? columns.get(columnIndex)
                                : columns.get(columnIndex) + " (continued " + (chunkIndex + 1) + ")";
                        header.createCell(excelColumnIndex++).setCellValue(headerValue);
                    }
                }
                jdbcTemplate.query("""
                        SELECT record_json FROM spn_records
                        WHERE upload_id = ? AND category_key = ? ORDER BY row_number
                        """, result -> {
                    int rowIndex = 1;
                    while (result.next()) {
                        Map<String, Object> record = readRecord(result.getString("record_json"));
                        Row row = sheet.createRow(rowIndex++);
                        int rowExcelColumnIndex = 0;
                        for (int columnIndex = 0; columnIndex < columns.size(); columnIndex++) {
                            Object value = record.get(columns.get(columnIndex));
                            if (value != null) {
                                String cellValue = exportCellValue(value);
                                for (int chunkIndex = 0; chunkIndex < chunkCounts.get(columnIndex); chunkIndex++) {
                                    int start = chunkIndex * EXCEL_CELL_CHARACTER_LIMIT;
                                    if (start < cellValue.length()) {
                                        int end = Math.min(start + EXCEL_CELL_CHARACTER_LIMIT, cellValue.length());
                                        row.createCell(rowExcelColumnIndex + chunkIndex).setCellValue(cellValue.substring(start, end));
                                    }
                                }
                            }
                            rowExcelColumnIndex += chunkCounts.get(columnIndex);
                        }
                    }
                    return null;
                }, uploadId, category.key());
            }
            workbook.write(output);
        }
    }

    private List<Integer> exportColumnChunkCounts(String uploadId, ExportCategory category) {
        List<Integer> chunkCounts = new ArrayList<>();
        category.columns().forEach(column -> chunkCounts.add(1));
        jdbcTemplate.query("""
                SELECT record_json FROM spn_records
                WHERE upload_id = ? AND category_key = ? ORDER BY row_number
                """, result -> {
            while (result.next()) {
                Map<String, Object> record = readRecord(result.getString("record_json"));
                for (int columnIndex = 0; columnIndex < category.columns().size(); columnIndex++) {
                    Object value = record.get(category.columns().get(columnIndex));
                    if (value != null) {
                        int requiredChunks = Math.max(1, (exportCellValue(value).length() + EXCEL_CELL_CHARACTER_LIMIT - 1)
                                / EXCEL_CELL_CHARACTER_LIMIT);
                        chunkCounts.set(columnIndex, Math.max(chunkCounts.get(columnIndex), requiredChunks));
                    }
                }
            }
            return null;
        }, uploadId, category.key());
        return chunkCounts;
    }

    private String uniqueSheetName(SXSSFWorkbook workbook, String label) {
        String base = WorkbookUtil.createSafeSheetName(label).replaceAll("\\s+", " ").trim();
        if (base.isBlank()) base = "Data";
        String candidate = base;
        int suffix = 2;
        while (workbook.getSheet(candidate) != null) {
            String ending = " (" + suffix++ + ")";
            candidate = base.substring(0, Math.min(base.length(), 31 - ending.length())) + ending;
        }
        return candidate;
    }

    private String exportCellValue(Object value) {
        if (value instanceof Map<?, ?> || value instanceof List<?>) return writeJson(value);
        return String.valueOf(value);
    }

    private void requireOwnedIncompleteUpload(String owner, String uploadId) {
        Integer count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM spn_uploads WHERE id = ? AND owner = ? AND completed = FALSE",
                Integer.class, uploadId, owner);
        if (count == null || count == 0) throw new IllegalArgumentException("Upload not found or already completed.");
    }

    private void requireOwnedCompleteUpload(String owner, String uploadId) {
        Integer count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM spn_uploads WHERE id = ? AND owner = ? AND completed = TRUE",
                Integer.class, uploadId, owner);
        if (count == null || count == 0) throw new IllegalArgumentException("Completed upload not found.");
    }

    private String writeJson(Object value) {
        try {
            return objectMapper.writeValueAsString(value);
        } catch (RuntimeException ex) {
            throw new IllegalArgumentException("Could not serialize SPN data.", ex);
        }
    }

    private Map<String, Object> readRecord(String value) {
        try {
            return objectMapper.readValue(value, new TypeReference<>() { });
        } catch (RuntimeException ex) {
            throw new IllegalStateException("Stored SPN record is invalid JSON.", ex);
        }
    }

    private List<String> readColumns(String value) {
        try {
            return objectMapper.readValue(value, new TypeReference<>() { });
        } catch (RuntimeException ex) {
            throw new IllegalStateException("Stored SPN category is invalid JSON.", ex);
        }
    }

    private String searchableText(String serializedRecord) {
        String text = serializedRecord.toLowerCase();
        // Keep the searchable copy bounded; the complete JSON remains in record_json.
        return text.length() > 16000 ? text.substring(0, 16000) : text;
    }

    private record StoredRecord(int rowNumber, Map<String, Object> payload) {
    }

    private record ExportCategory(String key, String label, List<String> columns) {
    }
}